services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    restart: "on-failure"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    restart: "on-failure"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
        - 27017:27017
    volumes:
        - .docker/mongo:/data/db
    restart: "on-failure"

  accountservice:
    build:
      context: ./accountservice
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - 8080:8080
    restart: "on-failure"

  accountstorage:
    build:
      context: ./accountstorage
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mongo
    ports:
      - 8081:8081
    restart: "on-failure"