spring:
  application:
    name: accountstorage
  data:
    mongodb:
      uri: mongodb://localhost:27017/account_db


  server:
    port: 8081

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
