spring:
  application:
    name: accountstorage

  server:
    port: 8081

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
