name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Extract Git commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push accountservice image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/accountservice:${{ env.COMMIT_HASH }} ./accountservice
          docker push ${{ secrets.DOCKER_USERNAME }}/accountservice:${{ env.COMMIT_HASH }}

      - name: Build and push accountstorage image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/accountstorage:${{ env.COMMIT_HASH }} ./accountstorage
          docker push ${{ secrets.DOCKER_USERNAME }}/accountstorage:${{ env.COMMIT_HASH }}
